evote/evotecore/urls.py
# -*- coding: utf-8 -*-
#
# eVotUM - Electronic Voting System
# Copyright (c) 2020 Universidade do Minho
# Developed by Eurotux (dev@eurotux.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


"""Evotecore URL configuration."""
from __future__ import unicode_literals

from django.conf.urls import url
from django.conf import settings

from evotevotings.admin.views import PageDetailView

from .views import DemoView, HomepageView


app_name = "evotecore"

urlpatterns = [
    url(
        regex=r'^$',
        view=HomepageView.as_view(),
        name="index"
    ),
    url(
        regex=r'page/(?P<slug>[-\w]+)/$',
        view=PageDetailView.as_view(),
        name="page-detail"
    ),
]


if settings.DEBUG:
    urlpatterns += [
        url(
            regex=r'^demo/$',
            view=DemoView.as_view(),
            name="demo"
        )
    ]

evote/evotevotings/management/urls.py
# -*- coding: utf-8 -*-
#
# eVotUM - Electronic Voting System
# Copyright (c) 2020 Universidade do Minho
# Developed by Eurotux (dev@eurotux.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


from __future__ import unicode_literals

from django.views.generic.base import RedirectView
from django.conf.urls import url
from django.conf import settings

from evoteusers.views import EvoteLogoutView

from .views import (ElectoralProcessListView, ElectoralProcessDetailView,
                    ElectoralProcessActionsView, ElectionListView,
                    ElectionDetailConfigsView, ElectionDetailCalendarView,
                    ElectionDetailCategoriesView, ElectionDetailRollsView,
                    ElectionDetailCandidatesView, ElectionDetailBulletinView,
                    ElectionDetailBulletinPreviewView,
                    LoginView, ElectoralProcessFormView,
                    ElectoralProcessMembersView, ElectoralProcessSummaryView,
                    ElectoralProcessConfirmationView,
                    ElectoralProcessElectionsView,
                    ElectoralProcessCommunicationView,
                    ElectionDetailRollsPublishView,
                    PersonalDataView, ElectionManageView,
                    ElectionManageCloseView, ElectionManageScrutinizeView,
                    MessageReceivedListView, MessageSentListView,
                    MessageArchivedListView, MessageCreateView,
                    MessageDetailView, MessageResponseView,
                    MessageArchiveView, ElectoralProcessMembersEditView,
                    GenerateCertificateView, ElectoralProcessSummaryPdfView,
                    ValidateEmailView, ResendPendingTokenMailView,
                    ElectionCountingsPDFView)

from .ajax import (SecureActionAjaxView, ManageSecureActionAjaxView,
                   ElectoralMemberVerifyView, ElectionCountingsPartialView,
                   ElectionScrutinyStatusView, AuthAmaAjaxView,
                   HistoryAjaxView, HistoryNewAjaxView)

app_name = "management"


urlpatterns = [
    url(
        regex=r'^$',
        view=RedirectView.as_view(url=settings.LOGIN_REDIRECT_URL),
        name="index"
    ),
    url(
        regex=r'^login/$',
        view=LoginView.as_view(),
        name="login"
    ),
    url(
        regex=r'^logout/$',
        view=EvoteLogoutView.as_view(),
        name="logout"
    ),
    url(
        regex=r'^personaldata/$',
        view=PersonalDataView.as_view(),
        name="personal-data"
    ),
    url(
        regex=r'^personaldata/resendemail/$',
        view=ResendPendingTokenMailView.as_view(),
        name="resend-email"
    ),
    url(
        regex=r'^personaldata/validateemail/$',
        view=ValidateEmailView.as_view(),
        name="validate-email"
    ),
    url(
        regex=r'^electoralprocess/$',
        view=ElectoralProcessListView.as_view(),
        name="electoralprocess-list"
    ),
    url(
        regex=r'^electoralprocess/new/$',
        view=ElectoralProcessFormView.as_view(),
        name="electoralprocess-new"
    ),
    # slug rules are greedy, order of urls is important here
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/$',
        view=ElectoralProcessDetailView.as_view(),
        name="electoralprocess-detail"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/received/$',
        view=MessageReceivedListView.as_view(),
        name="messages-received"
    ),

    # messages
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/sent/$',
        view=MessageSentListView.as_view(),
        name="messages-sent"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/archived/$',
        view=MessageArchivedListView.as_view(),
        name="messages-archived"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/new/$',
        view=MessageCreateView.as_view(),
        name="messages-create"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/(?P<pk>[-\d]+)/$',
        view=MessageDetailView.as_view(),
        name="messages-detail"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/(?P<pk>[-\d]+)/response/$',
        view=MessageResponseView.as_view(),
        name="messages-response"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/(?P<pk>[-\d]+)/archive/$',
        view=MessageArchiveView.as_view(),
        name="messages-archive"
    ),

    # electoral process
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/edit/$',
        view=ElectoralProcessFormView.as_view(),
        name="electoralprocess-edit"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/edit/elections/$',
        view=ElectoralProcessElectionsView.as_view(),
        name="electoralprocess-elections"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/members/$',
        view=ElectoralProcessMembersView.as_view(),
        name="electoralprocess-members-view"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/members/edit/$',
        view=ElectoralProcessMembersEditView.as_view(),
        name="electoralprocess-members-edit"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/communication/$',
        view=ElectoralProcessCommunicationView.as_view(),
        name="electoralprocess-communication"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/summary/$',
        view=ElectoralProcessSummaryView.as_view(),
        name="electoralprocess-summary"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/summary/pdf/$',
        view=ElectoralProcessSummaryPdfView.as_view(),
        name="electoralprocess-pdf"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/generate/$',
        view=GenerateCertificateView.as_view(),
        name="electoralprocess-generate"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/confirmation/$',
        view=ElectoralProcessConfirmationView.as_view(),
        name="electoralprocess-confirmation"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/actions/$',
        view=ElectoralProcessActionsView.as_view(),
        name="electoralprocess-actions"
    ),

    # elections
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/$',
        view=ElectionListView.as_view(),
        name="election-list"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/manage/$',
        view=ElectionManageView.as_view(),
        name="election-manage"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/manage/countingspdf/$',
        view=ElectionCountingsPDFView.as_view(),
        name="election-manage-pdf"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/manage/close/$',
        view=ElectionManageCloseView.as_view(),
        name="election-manage-close"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/manage/scrutinize/$',
        view=ElectionManageScrutinizeView.as_view(),
        name="election-manage-scrutinize"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/configs/$',
        view=ElectionDetailConfigsView.as_view(),
        name="election-detail-configs"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/calendar/$',
        view=ElectionDetailCalendarView.as_view(),
        name="election-detail-calendar"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/categories/$',
        view=ElectionDetailCategoriesView.as_view(),
        name="election-detail-categories"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/rolls/$',
        view=ElectionDetailRollsView.as_view(),
        name="election-detail-rolls"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/rolls/publish/$',
        view=ElectionDetailRollsPublishView.as_view(),
        name="election-detail-rolls-publish"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/candidates/$',
        view=ElectionDetailCandidatesView.as_view(),
        name="election-detail-candidates"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/bulletin/$',
        view=ElectionDetailBulletinView.as_view(),
        name="election-detail-bulletin"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/bulletin/preview$',
        view=ElectionDetailBulletinPreviewView.as_view(),
        name="election-detail-bulletin-preview"
    )
]

# ajax urls
urlpatterns += [
    url(

evote/evotevotings/management/templates/management/includes/candidate_form.html
{% load i18n thumbnail form_tags formset_tags %}

<tr data-formset-form="{{prefix}}">
    <td class="vtop col-logo">
        <div data-upload>
            {% thumbnail form.instance.logo "84x84" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
            {% empty %}
                <i class="ev-icon evi-add"></i>
            {% endthumbnail %}
            <span class="hidden">{{form.logo}}</span>
        </div>
    </td>
    <td class="vtop">{% prepare_field form.designation %}</td>
    <td class="vtop col-doc">

        <!-- Nested formset -->
        <div data-formset data-formset-prefix="{{form.formset.prefix}}">
            {{form.formset.non_field_errors}}
            {{form.formset.management_form}}

            <table class="pure-table">
                <thead>
                    <tr>
                        <th></th>
                        <th class="col-doc-designation">{% trans "Document Name" %}</th>
                        <th>{% trans "Document file" %}</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody data-formset-body="{{form.formset.prefix}}" data-sortable>

                    {% for f in form.formset %}
                        {% include "management/includes/ordered_documents_form.html" with form=f prefix=form.formset.prefix only %}
                    {% endfor %}

                </tbody>
            </table>

            <script type="form-template" data-formset-empty-form="{{form.formset.prefix}}">
                {% escapescript %}
                    {% include "management/includes/ordered_documents_form.html" with form=form.formset.empty_form prefix=form.formset.prefix only %}
                {% endescapescript %}
            </script>
        </div>
        <!-- Nested formset -->

    </td>
    <td class="vtop table-opt">
        {{form.id}}
        {{form.election}}
        <span class="hidden">{{ form.DELETE }}</span>
        <a href="#" data-formset-add="{{form.formset.prefix}}" title="{% trans 'Add new document line' %}" class="pull-left"><i class="ev-icon evi-doc"></i></a>
        <a href="#" data-formset-delete-button="{{prefix}}" title="{% trans 'Delete candidate line' %}" class="pull-right"><i class="ev-icon evi-delete"></i></a>
    </td>
</tr>

evote/evotevotings/management/templates/management/includes/election_manage_tabs.html
{% load i18n %}

<div class="pure-g pure-title-row">
    <div class="pure-u-1-2">
        <h1>{{election}}</h1>
    </div>
    <div class="pure-u-1-2">
        <a href="#" class="pure-button pure-button-round pure-button-primary pull-right" data-partial-url="{% url 'management:election-countings' process_pk=election.electoral_process_id pk=election.pk %}">{% trans "Total ballot papers in ballot box" %}</a>
    </div>
</div>

<div class="pure-menu pure-menu-horizontal pure-menu-tab">

    <ul class="pure-menu-list pull-right">
        <li class="pure-menu-item {% if tab == 'open' %}pure-menu-selected{% endif%}">
            <a class="pure-menu-link" href="{% if tab != 'open' %}{% url 'management:election-manage' slug=election.electoral_process.slug slug_election=election.slug %}{% else %}#{% endif %}" >
                {% trans "Open poll" %}
            </a>
        </li>
        <li class="pure-menu-item {% if tab == 'close' %}pure-menu-selected{% endif%}">
            <a class="pure-menu-link" href="{% if tab != 'close' %}{% url 'management:election-manage-close' slug=election.electoral_process.slug slug_election=election.slug %}{% else %}#{% endif %}">
                {% trans "Close poll" %}
            </a>
        </li>
        <li class="pure-menu-item {% if tab == 'scrutinize' %}pure-menu-selected{% endif %}{% if not election.can_manage_counting %}pure-menu-disabled{% endif %}">
            <a class="pure-menu-link" href="{% if tab != 'scrutinize' and election.can_manage_counting %}{% url 'management:election-manage-scrutinize' slug=election.electoral_process.slug slug_election=election.slug %}{% else %}#{% endif %}">
                {% trans "Ballot paper counting" %}
            </a>
        </li>
    </ul>
</div>
<div class="pure-menu-content"></div>

evote/evotevotings/management/templates/management/includes/election_tabs.html
{% load i18n %}

<div class="pure-menu pure-menu-horizontal pure-menu-tab">
    <h1 class="pure-menu-tab-title">{{election}}</h1>
    <ul class="pure-menu-list pull-right">
        <li class="pure-menu-item {% if tab == 'configs' %}pure-menu-selected{% endif%}">
            <a class="pure-menu-link" href="{% if tab != 'configs' %}{% url "management:election-detail-configs" slug=election.electoral_process.slug slug_election=election.slug %}{% else %}#{% endif %}">
                {% trans "Configuration" %}
            </a>
        </li>
        <li class="pure-menu-item {% if tab == 'calendar' %}pure-menu-selected{% endif %}{% if not election.can_change_calendar %}pure-menu-disabled{% endif %}">
            <a class="pure-menu-link" href="{% if tab != 'calendar' and election.can_change_calendar %}{% url "management:election-detail-calendar" slug=election.electoral_process.slug slug_election=election.slug %}{% else %}#{% endif %}">
                {% trans "Electoral timetable" %}
            </a>
        </li>
        <li class="pure-menu-item {% if tab == 'categories' %}pure-menu-selected{% endif %}{% if not election.can_change_categories %}pure-menu-disabled{% endif %}" title="{% if not election.can_change_categories %}{% trans 'Only can change categories if election has weighted votes and the definitive electoral roll is not published yet.' %}{% endif %}">
            <a class="pure-menu-link" href="{% if tab != 'categories' and election.can_change_categories %}{% url "management:election-detail-categories" slug=election.electoral_process.slug slug_election=election.slug %}{% else %}#{% endif %}">
                {% trans "Voting weight" %}
            </a>
        </li>
        <li class="pure-menu-item {% if tab == 'rolls' %}pure-menu-selected{% endif %}{% if not election.can_change_rolls %}pure-menu-disabled{% endif %}">
            <a class="pure-menu-link" href="{% if tab != 'rolls' and election.can_change_rolls %}{% url "management:election-detail-rolls" slug=election.electoral_process.slug slug_election=election.slug %}{% else %}#{% endif %}">
                {% trans "Electoral roll" %}
            </a>
        </li>
        <li class="pure-menu-item {% if tab == 'candidates' %}pure-menu-selected{% endif %}{% if not election.can_change_candidates %}pure-menu-disabled{% endif %}" title="{% if not election.can_change_candidates %}{% trans 'Only can change candidates if period for the submission of applications have been reached' %}{% endif %}">
            <a class="pure-menu-link" href="{% if tab != 'candidates' and election.can_change_candidates %}{% url "management:election-detail-candidates" slug=election.electoral_process.slug slug_election=election.slug %}{% else %}#{% endif %}">
                {% trans "Applications" %}
            </a>
        </li>
        <li class="pure-menu-item {% if tab == 'bulletin' %}pure-menu-selected{% endif%}{% if not election.can_change_bulletin %}pure-menu-disabled{% endif %}" title="{% if not election.can_change_bulletin %}{% trans 'Only can change ballot paper if election configurations has been filled and at least one candidate have been created' %}{% endif %}">
            <a class="pure-menu-link" href="{% if tab != 'bulletin' and election.can_change_bulletin %}{% url "management:election-detail-bulletin" slug=election.electoral_process.slug slug_election=election.slug %}{% else %}#{% endif %}">
                {% trans "Ballot" %}
            </a>
        </li>
    </ul>
</div>
<div class="pure-menu-content"></div>

evote/evotevotings/management/templates/management/includes/electoralprocess_document_form.html
{% load i18n form_tags formset_tags %}


<tr data-formset-form={{prefix}}>
    <td class="vtop">
        {% prepare_field form_elem.designation %}
    </td>
    <td class="vtop col-doc">

        <div data-formset data-formset-prefix="{{form_elem.formset.prefix}}">
            {{form_elem.formset.non_field_errors}}
            {{form_elem.formset.management_form}}
            {{form_elem.id}}
            <table class="pure-table">
                <thead>
                    <tr>
                        <th></th>
                        <th>{% trans "Document Name" %}</th>
                        <th>{% trans "Document file" %}</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody data-formset-body="{{form_elem.formset.prefix}}" data-sortable>
                    {% for f in form_elem.formset %}
                        {% include "management/includes/ordered_documents_form.html" with form=f prefix=form_elem.formset.prefix only %}
                    {% endfor %}
                </tbody>
            </table>
            <script type="form-template" data-formset-empty-form="{{form_elem.formset.prefix}}">
                {% escapescript %}
                    {% include "management/includes/ordered_documents_form.html" with form=form_elem.formset.empty_form prefix=form_elem.formset.prefix only %}
                {% endescapescript %}
            </script>
        </div>
    </td>
    <td class="vtop table-opt">
        <span class="hidden">{{form_elem.DELETE}}</span>
        <a href="#" data-formset-add="{{form_elem.formset.prefix}}" title="{% trans 'Add new document line' %}" class="pull-left"><i class="ev-icon evi-doc"></i></a>
        <a href="#" data-formset-delete-button="{{prefix}}" title="Delete document line" class="pull-right"><i class="ev-icon evi-delete"></i></a>
    </td>
</tr>

evote/evotevotings/management/templates/management/includes/electoralprocess_members_form.html
{% load i18n form_tags formset_tags ama_tags %}

<form id="members-form" action="" class="pure-form" method="post" novalidate data-ajax-submit data-js-reload>
    {% csrf_token %}
    <div data-formset data-formset-prefix="{{form.prefix}}">
        {{ form.non_field_errors }}
        {{ form.management_form }}

        <table class="pure-table pure-table-alt">
            <thead>
                <tr>
                    <th><label>{% trans 'Username' %}</label></th>
                    <th></th>
                    <th><label>{% trans 'Email address' %}</label></th>
                    <th><label>{% trans 'Name' %}</label></th>
                    <th><label>{% trans 'Designation' %}</label></th>
                    <th><label>{% trans 'Role' %}</label></th>
                    <th><label>{% trans 'Contact phone number' %}</label></th>
                    <th></th>
                </tr>
            </thead>
            <tbody data-formset-body="{{form.prefix}}">
                {% for form_elem in form %}
                    {% include "management/includes/member_form.html" with form_elem=form_elem prefix=form.prefix process_pk=object.pk only %}
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan=7 class="form-add">
                        <a href="#" data-formset-add="{{form.prefix}}" title="{% trans 'Add member' %}"><i class="ev-icon evi-addrow"></i></a>
                    </td>
                </tr>
            </tfoot>
        </table>
        <script type="form-template" data-formset-empty-form="{{form.prefix}}">
            {% escapescript %}
                {% include "management/includes/member_form.html" with form_elem=form.empty_form prefix=form.prefix process_pk=object.pk only %}
            {% endescapescript %}
        </script>
    </div>

    <div class="pure-g">
        {% if object.is_draft %}
            <div class="pure-u-1-2">
                <a href="{% url "management:electoralprocess-elections" slug=object.slug %}" class="pure-button pure-button-secondary pure-button-left pull-left">{% trans 'Previous' %}</a>
            </div>
            <div class="pure-u-1-2">
                <button type="submit" class="pure-button pure-button-primary pure-button-right pull-right">{% trans 'Next' %}</a>
            </div>
        {% else %}
            <div class="text-center pure-u-1">
                <button type="submit" class="pure-button pure-button-primary pure-button-smooth">{% trans 'Save' %}</button>
            </div>
        {% endif %}
    </div>
</form>

{% if not object.is_draft %}
    <div id="authform" class="hidden">
        {% url "management:electoralprocess-generate" slug=object.slug as succ_url %}
        {% url "management:electoralprocess-members-edit" slug=object.slug as error_url %}
        {% show_autenticacaogov_login succ_url error_url logo=False %}
    </div>
{% endif %}

evote/evotevotings/management/templates/management/includes/electoralprocess_tabs.html
{% load i18n %}

<div class="pure-menu pure-menu-horizontal pure-menu-tab">
    <h2 class="pure-menu-tab-title">
        {% if not object or object.is_draft %}
            {% trans 'Electoral process creation' %}
        {% else %}
            {% trans 'Electoral process edition' %}
        {% endif %}
    </h2>
    <ul class="pure-menu-list pull-right">
        <li class="pure-menu-item {% if general %}pure-menu-selected{% endif %}">
            {% if not object or object.is_draft %}
                <a class="pure-menu-link">{% trans 'General data' %}</a>
            {% else %}
                <a href="{% url "management:electoralprocess-edit" slug=object.slug %}" class="pure-menu-link">{% trans 'General data' %}</a>
            {% endif %}
        </li>
        {% if not request.user.is_electoral_member %}
            <li class="pure-menu-item {% if elections %}pure-menu-selected{% endif %}">
                {% if not object or object.is_draft %}
                    <a class="pure-menu-link">{% trans 'Elections' %}</a>
                {% else %}
                    <a href="{% url "management:electoralprocess-elections" slug=object.slug %}" class="pure-menu-link">{% trans 'Elections' %}</a>
                {% endif %}
            </li>
        {% endif %}
        <li class="pure-menu-item {% if members %}pure-menu-selected{% endif %}">
            {% if not object or object.is_draft %}
                <a class="pure-menu-link">{% trans 'Electoral commission' %}</a>
            {% elif request.user.is_electoral_member or not object.can_edit_members %}
                <a href="{% url "management:electoralprocess-members-view" slug=object.slug %}" class="pure-menu-link">{% trans 'Electoral commission' %}</a>
            {% else %}
                <a href="{% url "management:electoralprocess-members-edit" slug=object.slug %}" class="pure-menu-link">{% trans 'Electoral commission' %}</a>
            {% endif %}
        </li>
        {% if request.user.is_electoral_member and not object.is_draft %}
            <li class="pure-menu-item {% if comunication %}pure-menu-selected{% endif %}">
                <a href="{% url "management:electoralprocess-communication" slug=object.slug %}" class="pure-menu-link">{% trans 'Responsible for communication' %}</a>
            </li>
        {% endif %}
    </ul>
</div>

evote/evotevotings/management/templates/management/includes/electoralroll_publish_form.html
{% load i18n %}
<form action="{% url 'management:election-detail-rolls-publish' slug=object.election.electoral_process.slug slug_election=object.election.slug %}" data-secure-action="{{secure_action_url}}" data-ajax-submit method="POST">{% csrf_token %}
    <button type="submit" class="pure-button pure-button-secondary pure-button-round">{% trans "Publish electoral roll" %}</button>
</form>

evote/evotevotings/management/templates/management/includes/message_top.html
{% load i18n messages_tags %}

<div class="pure-g pure-gutter pure-title-row">
    <div class="pure-u-1 pure-u-md-1-2">
        <h1>{{title}}</h1>
    </div>
    <div class="pure-u-1 pure-u-md-1-2 ev-top-actions">
        <div class="pure-u-1-4 pull-right">
            <a href="{% url 'management:messages-archived' process_slug=group_object.slug %}" class="pure-button {% if is_archivedbox %}pure-button-primary{% else %}pure-button-secondary{% endif %} pure-button-round pull-right">{% trans 'Archived' %}</a>
        </div>
        <div class="pure-u-1-4 pull-right">
            <a href="{% url 'management:messages-sent' process_slug=group_object.slug %}" class="pure-button {% if is_sentbox %}pure-button-primary{% else %}pure-button-secondary{% endif %} pure-button-round pull-right">{% trans 'Sent' %}</a>
        </div>
        <div class="pure-u-1-4 pull-right">
            {% inbox_unread_count group_object=group_object as unread_count %}
            <a href="{% url 'management:messages-received' process_slug=group_object.slug %}" class="pure-button {% if is_inbox %}pure-button-primary{% else %}pure-button-secondary{% endif %} pure-button-round pull-right">
                {% trans 'Received' %}
                {% if unread_count %}
                    ({{unread_count}})
                {% endif %}
            </a>
        </div>
    </div>
</div>

<div class="action-bar">
    {% if is_comunication_responsible %}
        <a href="{% url 'management:messages-create' process_slug=group_object.slug %}" class="pure-button pure-button-small nobg pure-button-primary pure-button-round">{% trans 'New' context 'message' %} <i class="ev-icon evi-new-msg"></i></a>
    {% endif %}
</div>