evote/contrib/adfsauth/urls.py
# -*- coding: utf-8 -*-
#
# eVotUM - Electronic Voting System
# Copyright (c) 2020 Universidade do Minho
# Developed by Eurotux (dev@eurotux.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


"""adfsauth URL configuration."""

from django.conf.urls import url

from .views import WSFedSigninView, WSFedSignoutView


app_name = "adfsauth"

urlpatterns = [
    url(
        regex=r'^wsignin/$',
        view=WSFedSigninView.as_view(),
        name="ws-fed-signin"
    ),
    url(
        regex=r'^wsignout/$',
        view=WSFedSignoutView.as_view(),
        name="ws-fed-signout"
    )
]

evote/evotecore/urls.py
# -*- coding: utf-8 -*-
#
# eVotUM - Electronic Voting System
# Copyright (c) 2020 Universidade do Minho
# Developed by Eurotux (dev@eurotux.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


"""Evotecore URL configuration."""
from __future__ import unicode_literals

from django.conf.urls import url
from django.conf import settings

from evotevotings.admin.views import PageDetailView

from .views import DemoView, HomepageView


app_name = "evotecore"

urlpatterns = [
    url(
        regex=r'^$',
        view=HomepageView.as_view(),
        name="index"
    ),
    url(
        regex=r'page/(?P<slug>[-\w]+)/$',
        view=PageDetailView.as_view(),
        name="page-detail"
    ),
]


if settings.DEBUG:
    urlpatterns += [
        url(
            regex=r'^demo/$',
            view=DemoView.as_view(),
            name="demo"
        )
    ]

evote/evotevotings/management/urls.py
# -*- coding: utf-8 -*-
#
# eVotUM - Electronic Voting System
# Copyright (c) 2020 Universidade do Minho
# Developed by Eurotux (dev@eurotux.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


from __future__ import unicode_literals

from django.views.generic.base import RedirectView
from django.conf.urls import url
from django.conf import settings

from evoteusers.views import EvoteLogoutView

from .views import (ElectoralProcessListView, ElectoralProcessDetailView,
                    ElectoralProcessActionsView, ElectionListView,
                    ElectionDetailConfigsView, ElectionDetailCalendarView,
                    ElectionDetailCategoriesView, ElectionDetailRollsView,
                    ElectionDetailCandidatesView, ElectionDetailBulletinView,
                    ElectionDetailBulletinPreviewView,
                    LoginView, ElectoralProcessFormView,
                    ElectoralProcessMembersView, ElectoralProcessSummaryView,
                    ElectoralProcessConfirmationView,
                    ElectoralProcessElectionsView,
                    ElectoralProcessCommunicationView,
                    ElectionDetailRollsPublishView,
                    PersonalDataView, ElectionManageView,
                    ElectionManageCloseView, ElectionManageScrutinizeView,
                    MessageReceivedListView, MessageSentListView,
                    MessageArchivedListView, MessageCreateView,
                    MessageDetailView, MessageResponseView,
                    MessageArchiveView, ElectoralProcessMembersEditView,
                    GenerateCertificateView, ElectoralProcessSummaryPdfView,
                    ValidateEmailView, ResendPendingTokenMailView,
                    ElectionCountingsPDFView)

from .ajax import (SecureActionAjaxView, ManageSecureActionAjaxView,
                   ElectoralMemberVerifyView, ElectionCountingsPartialView,
                   ElectionScrutinyStatusView, AuthAmaAjaxView,
                   HistoryAjaxView, HistoryNewAjaxView)

app_name = "management"


urlpatterns = [
    url(
        regex=r'^$',
        view=RedirectView.as_view(url=settings.LOGIN_REDIRECT_URL),
        name="index"
    ),
    url(
        regex=r'^login/$',
        view=LoginView.as_view(),
        name="login"
    ),
    url(
        regex=r'^logout/$',
        view=EvoteLogoutView.as_view(),
        name="logout"
    ),
    url(
        regex=r'^personaldata/$',
        view=PersonalDataView.as_view(),
        name="personal-data"
    ),
    url(
        regex=r'^personaldata/resendemail/$',
        view=ResendPendingTokenMailView.as_view(),
        name="resend-email"
    ),
    url(
        regex=r'^personaldata/validateemail/$',
        view=ValidateEmailView.as_view(),
        name="validate-email"
    ),
    url(
        regex=r'^electoralprocess/$',
        view=ElectoralProcessListView.as_view(),
        name="electoralprocess-list"
    ),
    url(
        regex=r'^electoralprocess/new/$',
        view=ElectoralProcessFormView.as_view(),
        name="electoralprocess-new"
    ),
    # slug rules are greedy, order of urls is important here
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/$',
        view=ElectoralProcessDetailView.as_view(),
        name="electoralprocess-detail"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/received/$',
        view=MessageReceivedListView.as_view(),
        name="messages-received"
    ),

    # messages
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/sent/$',
        view=MessageSentListView.as_view(),
        name="messages-sent"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/archived/$',
        view=MessageArchivedListView.as_view(),
        name="messages-archived"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/new/$',
        view=MessageCreateView.as_view(),
        name="messages-create"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/(?P<pk>[-\d]+)/$',
        view=MessageDetailView.as_view(),
        name="messages-detail"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/(?P<pk>[-\d]+)/response/$',
        view=MessageResponseView.as_view(),
        name="messages-response"
    ),
    url(
        regex=r'^electoralprocess/(?P<process_slug>[-\w]+)/'
              'messages/(?P<pk>[-\d]+)/archive/$',
        view=MessageArchiveView.as_view(),
        name="messages-archive"
    ),

    # electoral process
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/edit/$',
        view=ElectoralProcessFormView.as_view(),
        name="electoralprocess-edit"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/edit/elections/$',
        view=ElectoralProcessElectionsView.as_view(),
        name="electoralprocess-elections"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/members/$',
        view=ElectoralProcessMembersView.as_view(),
        name="electoralprocess-members-view"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/members/edit/$',
        view=ElectoralProcessMembersEditView.as_view(),
        name="electoralprocess-members-edit"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/communication/$',
        view=ElectoralProcessCommunicationView.as_view(),
        name="electoralprocess-communication"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/summary/$',
        view=ElectoralProcessSummaryView.as_view(),
        name="electoralprocess-summary"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/summary/pdf/$',
        view=ElectoralProcessSummaryPdfView.as_view(),
        name="electoralprocess-pdf"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/generate/$',
        view=GenerateCertificateView.as_view(),
        name="electoralprocess-generate"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/confirmation/$',
        view=ElectoralProcessConfirmationView.as_view(),
        name="electoralprocess-confirmation"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/actions/$',
        view=ElectoralProcessActionsView.as_view(),
        name="electoralprocess-actions"
    ),

    # elections
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/$',
        view=ElectionListView.as_view(),
        name="election-list"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/manage/$',
        view=ElectionManageView.as_view(),
        name="election-manage"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/manage/countingspdf/$',
        view=ElectionCountingsPDFView.as_view(),
        name="election-manage-pdf"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/manage/close/$',
        view=ElectionManageCloseView.as_view(),
        name="election-manage-close"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/manage/scrutinize/$',
        view=ElectionManageScrutinizeView.as_view(),
        name="election-manage-scrutinize"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/configs/$',
        view=ElectionDetailConfigsView.as_view(),
        name="election-detail-configs"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/calendar/$',
        view=ElectionDetailCalendarView.as_view(),
        name="election-detail-calendar"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/categories/$',
        view=ElectionDetailCategoriesView.as_view(),
        name="election-detail-categories"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/rolls/$',
        view=ElectionDetailRollsView.as_view(),
        name="election-detail-rolls"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/rolls/publish/$',
        view=ElectionDetailRollsPublishView.as_view(),
        name="election-detail-rolls-publish"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/candidates/$',
        view=ElectionDetailCandidatesView.as_view(),
        name="election-detail-candidates"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/bulletin/$',
        view=ElectionDetailBulletinView.as_view(),
        name="election-detail-bulletin"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/elections/'
              r'(?P<slug_election>[-\w]+)/bulletin/preview$',
        view=ElectionDetailBulletinPreviewView.as_view(),
        name="election-detail-bulletin-preview"
    )
]

# ajax urls
urlpatterns += [
    url(

evote/evotevotings/management/templates/management/election_detail_bulletin_preview.html
{% extends "voters/election_voting_step1.html" %}

{% load i18n static %}

{% block voting_navigation %}
    <div class="voting-navigation text-center">
        <a href="{% url 'management:election-detail-bulletin' slug=object.electoral_process.slug slug_election=object.slug %}" class="pure-button pure-button-big pure-button-primary pure-button-smooth">{% trans "Close preview" %}</a>
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" charset="utf-8" src="{% static 'voters/js/main.jquery.js' %}"></script>
{% endblock extrajs %}

evote/evotevotings/management/templates/management/election_detail_categories.html
{% extends 'management/election_detail_configs.html' %}

{% load i18n core_tags form_tags formset_tags %}


{% block container %}
    <main class="wrap">
        {% include "management/includes/election_tabs.html" with election=object tab="categories" only %}

        <div class="pure-help">
            <i class="ev-icon evi-help"></i>
            {% trans "Please associate the Identifier (Id) with the voting weight" %}
        </div>

        <form class="pure-form" action="" method="post" novalidate data-ajax-submit data-secure-action="{{secure_action_url}}">{% csrf_token %}

            <div data-formset data-formset-prefix="{{form.prefix}}">
                {{form.management_form}}

                <table class="pure-table pure-table-alt">
                    <thead>
                        <th>{% trans "Id" %}</th>
                        <th class="s-40">{% trans "Description [PT]" %}</th>
                        <th class="s-40">{% trans "Description [EN]" %}</th>
                        <th class="s-10">{% trans "Weight" %}</th>
                        <th></th>
                    </thead>
                    <tbody data-formset-body="{{form.prefix}}">
                        {% with default_category=object.categories.default %}
                            {% if default_category %}
                                <tr>
                                    <td>{{default_category.slug}}</td>
                                    <td class="vtop">{{ default_category.designation_pt }}</td>
                                    <td class="vtop">{{ default_category.designation_en }}</td>
                                    <td class="vtop">{{ default_category.weight }}</td>
                                    <td></td>
                                </tr>
                            {% endif %}
                        {% endwith %}
                        {% for f in form %}
                            <tr data-formset-form="{{form.prefix}}">
                                <td>{{f.instance.slug}}</td>
                                <td class="vtop">{% prepare_field f.designation_pt %}</td>
                                <td class="vtop">{% prepare_field f.designation_en %}</td>
                                <td class="vtop">{% prepare_field f.weight %}</td>
                                <td class="text-right vtop">
                                    {{f.id}}
                                    {{f.election}}
                                    <span class="hidden">{{ f.DELETE }}</span>
                                    <a href="#" data-formset-delete-button="{{form.prefix}}" title="{% trans 'Delete line' %}"><i class="ev-icon evi-delete"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="5" class="form-add">
                                <a href="#" data-formset-add="{{form.prefix}}" title="{% trans 'Add new line' %}">
                                    <i class="ev-icon evi-addrow"></i>
                                </a>
                            </td>
                        </tr>
                    </tfoot>
                </table>

                <script type="form-template" data-formset-empty-form="{{form.prefix}}">
                    {% escapescript %}
                        <tr data-formset-form="{{form.prefix}}">
                            <td class="vtop"></td>
                            <td class="vtop">{% prepare_field form.empty_form.designation_pt %}</td>
                            <td class="vtop">{% prepare_field form.empty_form.designation_en %}</td>
                            <td class="vtop">{% prepare_field form.empty_form.weight %}</td>
                            <td class="text-right vtop">
                                {{form.empty_form.id}}
                                {{form.empty_form.election}}
                                <span class="hidden">{{ form.empty_form.DELETE }}</span>
                                <a href="#" data-formset-delete-button="{{form.prefix}}"><i class="ev-icon evi-delete"></i></a>
                            </td>
                        </tr>
                    {% endescapescript %}
                </script>

            </div>
            <div class="text-center pure-u-1">
                <button type="submit" class="pure-button pure-button-primary pure-button-smooth">{% trans "Save" %}</button>
            </div>

        </form>
    </main>
{% endblock container %}

evote/evotevotings/management/templates/management/election_detail_rolls.html
{% extends 'management/election_detail_configs.html' %}

{% load i18n core_tags form_tags django_tables2 %}


{% block container %}
    <main class="wrap">
        {% include "management/includes/election_tabs.html" with election=object tab="rolls" only %}

        <div class="pure-help">
            <i class="ev-icon evi-help"></i>
            {% trans "Please upload the file with the voters" %}
        </div>

        <form class="pure-form" action="" method="post" novalidate data-ajax-submit>{% csrf_token %}
            {{form.non_field_errors}}

            <table class="pure-table pure-table-alt">
                <thead>
                    <tr>
                        <th class="s-25">{% trans "Description" %}</th>
                        <th>{% trans "Document" %}</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="row-pure-button">
                        <td class="vtop">{% prepare_field form.designation %}</td>
                        <td class="vtop">{% prepare_field form.document %}</td>
                        <td class="text-right vtop"><button type="submit" class="pure-button pure-button-primary pure-button-round" {% if form.is_importing %}disabled{% endif %}>{% trans "Submit" %}</button></td>
                    </tr>
                </tbody>
            </table>
        </form>

        {% render_table table %}

        <small>&#x21bb; - {% trans "refresh the page to update the status" %}</small>
    </main>
{% endblock container %}

evote/evotevotings/management/templates/management/electoralprocess_list.html
{% extends 'management/base.html' %}

{% load i18n thumbnail core_tags django_tables2 %}


{% block breadcrumbs %}{% endblock breadcrumbs %}


{% block container %}
    <main class="wrap">
        <div class="pure-g pure-gutter pure-title-row">
            <div class="pure-u-1 pure-u-md-1-2">
                <h1>{% trans 'Electoral Processes' %}</h1>
            </div>
            {% if request.user.is_institutional_responsible %}
                <div class="pure-u-1 pure-u-md-1-2 ev-top-actions">
                    <a href="{% url 'management:electoralprocess-new' %}" class="pure-button pure-button-secondary pure-button-round pull-right">{% trans 'New electoral process' %}</a>
                </div>
            {% endif %}
        </div>
        {% render_table table %}
    </main>
{% endblock container %}

evote/evotevotings/management/templates/management/generate_certificate.html
{% extends "management/base.html" %}

{% load static i18n core_tags form_tags %}

{% block breadcrumbs %}
    {{block.super}}
    {% if process.is_draft %}
        {% trans 'New' as title %}
        {% breadcrumb title context 'electoral process' %}
    {% else %}
        {% breadcrumb process "management:electoralprocess-detail" slug=process.slug %}
        {% trans 'Certificate' as certificate %}
        {% breadcrumb certificate %}
    {% endif %}
{% endblock breadcrumbs %}

{% block extrajs %}
    <script type="text/javascript" src="{% static 'javascript-settings.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'vendor/evotum-cripto/dist/evotum.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'management/js/certificates.jquery.js' %}"></script>
{% endblock extrajs %}

{% block container %}
    <main class="wrap">
        <div class="pure-g">
            <div class="pure-u-1">
                <div class="pure-help">
                    <i class="ev-icon evi-help"></i>
                    {% trans 'Generate digital certificate and voting private cipher key and, its splitted secret (sent to the members of the electoral commission)' %}
                </div>
            </div>
            <div class="pure-u-1">
                <form class="pure-form" novalidate data-csr-sign data-members={{process.electoral_members.count}} data-areyousure-off>
                    {% csrf_token %}
                    <section class="pure-sec-block">
                        <div class="pure-form pure-sec-body">
                            <div class="pure-g pure-gutter">
                                <div class="pure-u-1">
                                    <label>{{form_render.password.label_tag}}</label>
                                    <div class="pure-g">
                                        <div class="pure-u-1 pure-u-md-1-5">
                                            {% prepare_field form_render.password %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    <fieldset data-field-csrs>
                        {% for field in form_render.get_elections_fields %}
                            {{field}}
                        {% endfor %}
                    </fieldset>
                    {{form_render.ca_cert}}
                    {{form_render.ca_pvt_key}}
                </form>
            </div>
            <div class="pure-u-1">
                <form class="pure-form" data-final-form action="" method="post" novalidate data-ajax-submit data-areyousure-off>
                    {% csrf_token %}
                    {{form.non_field_errors}}
                    {{form.elec_pvt_key}}
                    <fieldset data-field-members>
                        {% for field in form.get_members_fields %}
                            {{field}}
                        {% endfor %}
                    </fieldset>
                    <fieldset data-field-certs>
                        {% for field in form.get_elections_fields %}
                            {{field}}
                        {% endfor %}
                    </fieldset>

                    {% if process.is_draft %}
                        <a href="{% url "management:electoralprocess-summary" slug=process.slug %}" class="pure-button pure-button-secondary pure-button-left">{% trans "Previous" %}</a>
                    {% else %}
                        <a href="{% url "management:electoralprocess-members-edit" slug=process.slug %}" class="pure-button pure-button-secondary pure-button-left">{% trans "Previous" %}</a>
                    {% endif %}
                    <button data-csr-button type="submit" class="pure-button pure-button-primary pure-button-right pull-right">{% trans "Generate" %}</button>
                </form>
            </div>
        </div>
    </main>
{% endblock container %}

evote/evotevotings/management/templates/management/login.html
{% extends "management/base.html" %}

{% load form_tags i18n %}


{% block breadcrumbs_wrapper %}
{% endblock breadcrumbs_wrapper %}


{% block container %}
    <main class="wrap login-page">

        {% if ADFS_WSFED and user.is_authenticated %}

            <h1>{% trans 'Select profile' %}</h1>

            <div class="pure-help">
                <i class="ev-icon evi-help"></i>
                {% trans 'You are now authenticated.' %}<br/>
                {% trans 'Select the profile for your user, each profile has different privileges.' %}
            </div>

            <div class="login-box pure-form">
                <form action="" method="POST" novalidate autocomplete="off" data-areyousure-off>
                    {% csrf_token %}
                    <div class="pure-field">
                        {{ form.profile }}
                    </div>
                    <input class="pure-button pure-button-primary pure-button-smooth" type="submit" value="{% trans 'Select profile' %}" />
                </form>
            </div>

        {% elif not user.is_authenticated %}

            <h1>{% trans 'Authentication' %}</h1>

            {% if ADFS_WSFED %}

                <div class="pure-help">
                    <i class="ev-icon evi-help"></i>
                    {% trans 'Login required.' %}<br/>
                    {% trans 'Make external login to access Election management system.' %}
                </div>

                <div class="login-box">
                    <a href="{% url 'adfsauth:ws-fed-signin' %}" class="pure-button pure-button-primary pure-button-smooth">{% trans 'Login' %}</a>
                </div>

            {% else %}

                <div class="login-box pure-form">
                    <form action="" method="POST" novalidate autocomplete="off" data-areyousure-off>
                        {% csrf_token %}
                        {% prepare_field form.username "fi-avatar" True %}
                        {% prepare_field form.password "fi-lock" True %}
                        <div class="pure-field">
                            {{ form.profile }}
                        </div>
                        <input class="pure-button pure-button-primary pure-button-smooth" type="submit" value="{% trans 'Login' %}" />
                    </form>
                </div>
            {% endif %}

        {% endif %}
    </main>
{% endblock container %}

evote/evotevotings/management/templates/management/message_detail.html
{% extends "management/base.html" %}

{% load i18n core_tags messages_tags %}


{% block breadcrumbs %}
    {{block.super}}
    {% breadcrumb group_object "management:electoralprocess-detail" slug=group_object.slug %}
    {% trans "Messages" as title %}
    {% breadcrumb title "management:messages-received" process_slug=group_object.slug %}
    {% if object.is_sent %}
        {% trans "Sent" as sent %}
        {% breadcrumb sent "management:messages-sent" process_slug=group_object.slug %}
    {% elif object.is_archived %}
        {% trans "Archived" as archived %}
        {% breadcrumb archived "management:messages-archived" process_slug=group_object.slug %}
    {% endif %}
    {% breadcrumb object.subject %}
{% endblock breadcrumbs %}


{% block container %}
    <main class="wrap">

        {% include "management/includes/message_top.html" with title=object.subject %}

        <div class="message">
            <div class="pure-g">
                <div class="pure-u-21-24">
                    <div class="pure-g">
                        <div class="pure-u-1">
                            <label>{% trans 'From' %}:</label>
                            <span class="pure-label">{{object.sender}}</span>
                        </div>
                    </div>
                    <div class="pure-g">
                        <div class="pure-u-1">
                            <label>{% trans 'To' %}:</label>
                            {% for recipient in object|recipient_groups %}
                                <span class="pure-label">{{recipient}}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="pure-g">
                        <div class="pure-u-1">
                            <label>{% trans 'Subject' %}:</label> {{object.subject}}
                        </div>
                    </div>
                    <hr>
                    <div class="pure-g">
                        <div class="pure-u-1 message-body">
                            {{object.body|linebreaks}}
                        </div>
                    </div>
                </div>
                <div class="pure-u-3-24">
                    <label class="pull-right"><small>{{object.created}}</small></label>
                    <div class="message-actions">
                        {% if is_comunication_responsible and object.is_received %}
                            <a href="{% url 'management:messages-response' process_slug=group_object.slug pk=object.pk %}" class="message-action" title="{% trans 'Reply' %}"><i class="ev-icon evi-reponse"></i></a>
                        {% endif %}
                        {% if object.is_received %}
                            <form action="{% url 'management:messages-archive' pk=object.pk process_slug=group_object.slug %}" class="message-action" method="POST">{% csrf_token %}
                                <input type="hidden" name="id" value="{{object.pk}}">
                                <button type="submit" class="message-archive" title="{% trans 'Archive' %}"><i class="ev-icon evi-archive-state"></i></a>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="pure-g">
            <div class="pure-u-1 pull-right">
                {% if object.is_received %}
                    {% url 'management:messages-received' process_slug=group_object.slug as back_url %}
                {% elif object.is_sent %}
                    {% url 'management:messages-sent' process_slug=group_object.slug as back_url %}
                {% elif object.is_archived %}
                    {% url 'management:messages-archived' process_slug=group_object.slug as back_url %}
                {% endif %}

                <a href="{{back_url}}" class="pure-button pure-button-primary pure-button-round pull-right">
                    {% trans 'Back' %}
                </a>
            </div>
        </div>
    </main>

{% endblock container %}