evote/evotecore/urls.py
# -*- coding: utf-8 -*-
#
# eVotUM - Electronic Voting System
# Copyright (c) 2020 Universidade do Minho
# Developed by Eurotux (dev@eurotux.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


"""Evotecore URL configuration."""
from __future__ import unicode_literals

from django.conf.urls import url
from django.conf import settings

from evotevotings.admin.views import PageDetailView

from .views import DemoView, HomepageView


app_name = "evotecore"

urlpatterns = [
    url(
        regex=r'^$',
        view=HomepageView.as_view(),
        name="index"
    ),
    url(
        regex=r'page/(?P<slug>[-\w]+)/$',
        view=PageDetailView.as_view(),
        name="page-detail"
    ),
]


if settings.DEBUG:
    urlpatterns += [
        url(
            regex=r'^demo/$',
            view=DemoView.as_view(),
            name="demo"
        )
    ]

evote/evotevotings/voters/urls.py
# -*- coding: utf-8 -*-
#
# eVotUM - Electronic Voting System
# Copyright (c) 2020 Universidade do Minho
# Developed by Eurotux (dev@eurotux.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


from __future__ import unicode_literals

from django.views.generic.base import RedirectView
from django.conf.urls import url
from django.conf import settings

from evotevotings.admin.views import PageDetailView
from .views import (LoginView, ElectoralProcessListView,
                    ElectoralProcessArchiveView, ElectoralProcessDetailView,
                    ElectionHistoryView, ElectoralProcessVotingView,
                    ElectionVotingStep1View, ElectionVotingStep2View,
                    ElectionVotingStep3View, ElectionVotingStep3PinView,
                    ElectionVotingStep4View, ElectionSearchVoteView,
                    ContactsView, PersonalDataView, ElectionClaimMessageView,
                    SearchView, HowitworksView, ElectoralRollDetailView,
                    ValidateEmailView, ResendPendingTokenMailView,
                    MessageReceivedListView, MessageSentListView,
                    MessageArchivedListView, MessageCreateView,
                    MessageDetailView, MessageArchiveView, LogoutView)

from .ajax import VoteReferencesAjaxView

app_name = "voters"

urlpatterns = [
    url(
        regex=r'^$',
        view=RedirectView.as_view(url=settings.LOGIN_REDIRECT_URL),
        name="index"
    ),
    url(
        regex=r'^login/$',
        view=LoginView.as_view(),
        name="login"
    ),
    url(
        regex=r'^logout/$',
        view=LogoutView.as_view(),
        name="logout"
    ),
    url(
        regex=r'^contacts/$',
        view=ContactsView.as_view(),
        name="contacts"
    ),
    url(
        regex=r'^page/(?P<slug>[-\w]+)/$',
        view=PageDetailView.as_view(),
        name="page-detail"
    ),
    url(
        regex=r'^search/$',
        view=SearchView.as_view(),
        name="search"
    ),
    url(
        regex=r'^howitworks/$',
        view=HowitworksView.as_view(),
        name="howitworks"
    ),
    url(
        regex=r'^personaldata/$',
        view=PersonalDataView.as_view(),
        name="personal-data"
    ),
    url(
        regex=r'^personaldata/validateemail/$',
        view=ValidateEmailView.as_view(),
        name="validate-email"
    ),
    url(
        regex=r'^personaldata/resendemail/$',
        view=ResendPendingTokenMailView.as_view(),
        name="resend-email"
    ),

    # messages
    url(
        regex=r'^messages/received/$',
        view=MessageReceivedListView.as_view(),
        name="messages-received"
    ),
    url(
        regex=r'^messages/sent/$',
        view=MessageSentListView.as_view(),
        name="messages-sent"
    ),
    url(
        regex=r'^messages/archived/$',
        view=MessageArchivedListView.as_view(),
        name="messages-archived"
    ),
    url(
        regex=r'^messages/new/$',
        view=MessageCreateView.as_view(),
        name="messages-create"
    ),
    url(
        regex=r'^messages/(?P<pk>[-\d]+)/$',
        view=MessageDetailView.as_view(),
        name="messages-detail"
    ),
    url(
        regex=r'^messages/(?P<pk>[-\d]+)/archive/$',
        view=MessageArchiveView.as_view(),
        name="messages-archive"
    ),

    # electoral process
    url(
        regex=r'^electoralprocess/$',
        view=ElectoralProcessListView.as_view(),
        name="electoralprocess-list"
    ),
    url(
        regex=r'^electoralprocess/archive/$',
        view=ElectoralProcessArchiveView.as_view(),
        name="electoralprocess-archive"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/$',
        view=ElectoralProcessDetailView.as_view(),
        name="electoralprocess-detail"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/' +
        'electoralroll/(?P<slug_roll>[-\w]+)/$',
        view=ElectoralRollDetailView.as_view(),
        name="electoralroll-detail"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/(?P<slug_election>[-\w]+)/'
              r'claim/$',
        view=ElectionClaimMessageView.as_view(),
        name="election-claim"
    ),
    url(
        regex=r'^electoralprocess/(?P<slug>[-\w]+)/(?P<slug_election>[-\w]+)/'
              r'search/$',
        view=ElectionSearchVoteView.as_view(),
        name="election-search-vote"
    ),
    url(
        regex=r'^election/history/$',
        view=ElectionHistoryView.as_view(),
        name="election-history"
    ),
    # slug rules are greedy, order of urls is important here
    url(
        regex=r'^(?P<slug>[-\w]+)/vote/$',
        view=ElectoralProcessVotingView.as_view(),
        name="electoralprocess-voting"
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)/vote/(?P<slug_election>[-\w]+)/step1/$',
        view=ElectionVotingStep1View.as_view(),
        name="election-voting-step1"
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)/vote/(?P<slug_election>[-\w]+)/step2/$',
        view=ElectionVotingStep2View.as_view(),
        name="election-voting-step2"
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)/vote/(?P<slug_election>[-\w]+)/step3/$',
        view=ElectionVotingStep3View.as_view(),
        name="election-voting-step3"
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)/vote/(?P<slug_election>[-\w]+)/step3/pin/$',
        view=ElectionVotingStep3PinView.as_view(),
        name="election-voting-step3-pin"
    ),
    url(
        regex=r'^(?P<slug>[-\w]+)/vote/(?P<slug_election>[-\w]+)/step4/$',
        view=ElectionVotingStep4View.as_view(),
        name="election-voting-step4"
    ),
]

# ajax urls
urlpatterns += [
    url(
        regex=r'^(?P<pk>[-\d]+)/vote/(?P<pk_election>[-\d]+)/search/next$',
        view=VoteReferencesAjaxView.as_view(),
        name="vote-reference-next-page"
    ),
]

evote/evotevotings/voters/views.py
# -*- coding: utf-8 -*-
#
# eVotUM - Electronic Voting System
# Copyright (c) 2020 Universidade do Minho
# Developed by Eurotux (dev@eurotux.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


from __future__ import unicode_literals

import logging

from django.utils.six.moves.urllib.parse import urlparse
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.utils.encoding import force_text
from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import get_object_or_404, redirect
from django.conf import settings
from django.http import Http404

from evotevotings.processes.recipients import \
    ElectoralCommissionRecipientsGroup
from evotevotings.processes.models import ElectoralProcess
from evotevotings.elections.models import Election
from evotevotings.elections.utils import get_extra_election_data
from evoteajaxforms.views import FormJsonSimpleView, AjaxResponseAction
from evotemessages.views import (MessageReceivedListMixin,
                                 MessageSentListMixin, MessageDetailMixin,
                                 MessageArchivedListMixin, MessageCreateMixin,
                                 MessageArchiveMixin)
from evoteajaxforms.views import FormJsonView
from evotemessages.utils import gen_uid
from contrib.ama.utils import get_attributes
from evotesearch.views import SearchMixin
from evotecore.mixins import (DjangoTablesFilterMixin, PermissionListMixin,
                              PermissionRequiredMixin, SelectedMenuMixin)
from evoteusers.views import (EvoteLoginView, PersonalDataBaseView,
                              ValidateEmailBaseView,
                              ResendPendingTokenMailBaseView, EvoteLogoutView)
from evotecore.mixins import FeedbackMessageMixin
from evotecore.views import ErrorBaseView

from .mailings import ContactMail
from .filters import (ArchiveFilter, ElectionHistoryFilter, IndexFilter,
                      VoterFilter)
from .tables import (ElectoralProcessTable, ElectoralProcessArchiveTable,
                     ElectoralProcessMyTable, ElectionHistoryTable,
                     ElectionVoterTable)
from .models import ElectionVoter, ElectoralRoll
from .forms import (ElectionVotingStep1Form, ElectionVotingStep3Form,
                    ElectionVotingStep3PinForm, ElectionSearchVoteForm,
                    ContactsForm, ElectionClaimMessageForm)
from .utils import get_references, pin_expiration_date
from .menus import Menu


security_logger = logging.getLogger("evote.security")


class LoginView(EvoteLoginView):
    """Provides user the ability to login"""
    use_adfs = getattr(settings, "ADFS_WSFED", False)
    template_name = "voters/login.html"

    def dispatch(self, request, *args, **kwargs):
        """ """
        if self.use_adfs and request.user.is_authenticated():
            return redirect(settings.LOGIN_REDIRECT_URL)
        return super(LoginView, self).dispatch(request, *args, **kwargs)


class LogoutView(EvoteLogoutView):
    """Provides users the ability to logout"""

    def get_redirect_url(self):
        return reverse("evotecore:index")


class ElectoralProcessListView(
        SelectedMenuMixin, PermissionListMixin, DjangoTablesFilterMixin,
        ListView):
    """
    Shows the main view
    """
    model = ElectoralProcess
    queryset = ElectoralProcess.objects.published()
    permission_required = "evoteprocesses.view_electoralprocess"
    # tables
    table_pagination = {'per_page': 5}
    # filters
    filter_class = IndexFilter

    def get_table_class(self):
        if self.request.user.is_authenticated():
            return ElectoralProcessMyTable
        return ElectoralProcessTable

    def get_template_names(self):
        if self.request.user.is_authenticated():
            return ["voters/electoralprocess_mylist.html"]
        return ["voters/electoralprocess_list.html"]


class ElectoralProcessDetailView(
        SelectedMenuMixin, PermissionRequiredMixin, DetailView):
    """
    Shows the Electoral Process Detail view
    """
    model = ElectoralProcess
    permission_required = "evoteprocesses.view_electoralprocess"

    def get_template_names(self):
        if self.request.user.is_authenticated():
            return ["voters/electoralprocess_mydetail.html"]
        return ["voters/electoralprocess_detail.html"]

    def get_context_data(self, **kwargs):
        context = super(ElectoralProcessDetailView, self)\
            .get_context_data(**kwargs)
        context.update({
            'show_vote_link': self.object.elections.eligible(self.request.user)
            .in_to_vote().exists(),
            'state_scrutinized': Election.State.VOTES_SCRUTINIZED
        })
        return context


class ElectoralProcessArchiveView(
        SelectedMenuMixin, PermissionListMixin, DjangoTablesFilterMixin,
        ListView):
    """
    Shows the archive view
    """
    model = ElectoralProcess
    queryset = ElectoralProcess.objects.closed()
    permission_required = "evoteprocesses.view_electoralprocess"
    template_name = "voters/electoralprocess_archive.html"
    # tables
    table_class = ElectoralProcessArchiveTable
    table_pagination = {'per_page': 5}
    # filters
    filter_class = ArchiveFilter


class ContactsView(SelectedMenuMixin, FormJsonSimpleView):
    """ """
    prefix = 'contacts'
    form_class = ContactsForm
    template_name = "voters/contacts.html"
    action = AjaxResponseAction.REFRESH
    selected_menu = Menu.CONTACTS
    success_message = _("Your request was submitted successfully.")

    def form_valid(self, form):
        context = {
            'name': form.cleaned_data.get('name', ''),
            'from': form.cleaned_data.get('email', ''),
            'subject': form.cleaned_data.get('subject', ''),
            'message': form.cleaned_data.get('message', '')
        }
        ContactMail(context).send()
        return super(ContactsView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        """ """
        context = super(ContactsView, self).get_context_data(**kwargs)
        context.update({
            'name': getattr(settings, "EVOTE_CONTACT_NAME"),
            'email': getattr(settings, "EVOTE_CONTACT_MAIL"),
            'phone': getattr(settings, "EVOTE_CONTACT_PHONE"),
            'address': getattr(settings, "EVOTE_CONTACT_ADDRESS"),
            'map_gps': getattr(settings, "EVOTE_CONTACT_GPS", None)
        })
        return context


@method_decorator(login_required, name="dispatch")
class PersonalDataView(SelectedMenuMixin, PersonalDataBaseView):
    """ """
    template_name = "voters/personal_data.html"
    selected_menu = Menu.PERSONALDATA

    def get_form_kwargs(self):
        """ """
        form_kwargs = super(PersonalDataView, self).get_form_kwargs()
        form_kwargs.update({
            'base_url': self.request.build_absolute_uri(
                reverse("voters:validate-email"))
        })
        return form_kwargs

    def get_context_data(self, **kwargs):
        context = super(PersonalDataView, self).get_context_data(**kwargs)
        context.update({
            'resend_url': reverse_lazy("voters:resend-email")
        })
        return context


class ValidateEmailView(ValidateEmailBaseView):
    """ """
    template_name = "voters/validate_email.html"


@method_decorator(login_required, name="dispatch")
class ResendPendingTokenMailView(ResendPendingTokenMailBaseView):
    """ Resends email with token """

    def get_redirect_url(self):
        return reverse_lazy("voters:personal-data")

    def get_base_validate_url(self):
        return reverse("voters:validate-email")


class SearchView(SearchMixin, TemplateView):
    """ View showing search results from the base search query """
    template_name = "voters/search.html"


class HowitworksView(SelectedMenuMixin, TemplateView):
    """ """
    template_name = "voters/howitworks.html"
    selected_menu = Menu.HOWDOESITWORK


@method_decorator(login_required, name="dispatch")
class ElectionHistoryView(
        SelectedMenuMixin, PermissionListMixin, DjangoTablesFilterMixin,
        ListView):
    """
    Shows the my elections history view
    """
    model = Election
    queryset = Election.objects.closed()
    permission_required = "evoteelections.view_election"
    template_name = "voters/election_history.html"
    # tables
    table_class = ElectionHistoryTable
    table_pagination = {'per_page': 5}
    # filters
    filter_class = ElectionHistoryFilter
    selected_menu = Menu.HISTORICAL


"""
VOTING VIEWS
"""


@method_decorator(login_required, name="dispatch")
class ElectoralProcessVotingView(
        SelectedMenuMixin, PermissionRequiredMixin, DetailView):
    """
    Shows the voting system
    """
    model = ElectoralProcess
    permission_required = "evoteprocesses.view_electoralprocess"
    template_name = "voters/electoralprocess_voting.html"

    def get_context_data(self, **kwargs):
        """ """
        context = super(ElectoralProcessVotingView, self)\
            .get_context_data(**kwargs)
        elections = self.object.elections.eligible(self.request.user)\
            .in_to_vote()
        context.update({

evote/evotevotings/voters/templates/voters/includes/candidate_dropdown.html
{% load i18n static thumbnail %}

<div class="candidate-box">
    <img data-candidate-logo class="candidate-logo" src="{% static 'images/avatar.png' %}" width="85" height="85" alt="{% trans 'candidate' %}">
    <div class="candidate-designation">
        <select data-select-vote data-style-select id="{{candidate_list_attr.auto_id}}" name="{{candidate_list_attr.name}}" class="pure-select" {{extra_attrs}}>
            {% for candidate,candidate_label in candidate_list %}
                {% if candidate and candidate.logo %}
                    {% thumbnail candidate.logo "85x85" crop="center" as im %}
                        <option data-logo="{{im.url}}" value="{{candidate.id}}">{{candidate_label}}</option>
                    {% endthumbnail %}
                {% elif candidate %}
                    <option data-logo="{% static 'images/avatar.png' %}" value="{{candidate.id}}">{{candidate_label}}</option>
                {% else %}
                    <option data-logo="{% static 'images/avatar.png' %}" value="">{{candidate_label}}</option>
                {% endif %}
            {% endfor %}
        </select>
    </div>
    <label for="field" class="pure-checkbox no-selectable">
        <input data-vote-simulation name="vote" value="" type="checkbox">
        <span></span>
    </label>
</div>

evote/evotevotings/voters/templates/voters/includes/candidate_list.html
{% load i18n static thumbnail %}
{% for candidate,candidate_field in candidate_list %}
    <div data-vote-option class="candidate-box">
        {% if candidate.logo %}
            {% thumbnail candidate.logo "85x85" crop="center" as im %}
                <img data-candidate-logo class="candidate-logo" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{% trans 'candidate' %}">
            {% endthumbnail %}
        {% else %}
            <img data-candidate-logo class="candidate-logo" src="{% static 'images/avatar.png' %}" width="85" height="85" alt="{% trans 'candidate' %}">
        {% endif %}
        <div class="candidate-designation">
            <p data-candidate-designation>{{candidate.designation}}</p>
        </div>
        <label for="{{candidate_field.attrs.id}}" class="pure-checkbox">
            <input data-vote-checkbox id="{{candidate_field.attrs.id}}" name="{{candidate_field.name}}" value="{{candidate_field.choice_value}}" type="checkbox">
            <span></span>
        </label>
    </div>
{% endfor %}

evote/evotevotings/voters/templates/voters/includes/electoralprocess_detail.html
{% load i18n guardian_tags voters_tags %}

<main class="wrap">
    <div class="pure-g pure-title-row">
        {% if user.is_authenticated and show_vote_link %}
            <div class="pure-u-1 pure-u-md-4-5">
                <h1>{{object.identifier}}</h1>
            </div>
            <div class="pure-u-1 pure-u-md-1-5">
                <a href="{% url 'voters:electoralprocess-voting' slug=object.slug %}" class="pure-button pure-button-primary pure-button-round pull-right">{% trans 'Vote' %}</a>
            </div>
        {% else %}
            <div class="pure-u-1">
                <h1>{{object.identifier}}</h1>
            </div>
        {% endif %}
    </div>

    <section class="pure-sec-block">
        <h2 class="pure-block-title">{% trans 'General Information' %}</h2>
        <div class="pure-sec-body full-row">
            <div class="pure-description">
                {{object.description}}
            </div>
            {% for document in object.electoral_documents.all %}
                <div class="pure-g pure-sec-row">
                    <label class="pure-u-1 pure-u-md-2-5">{{document.designation}}</label>
                    {% if document.documents.all %}
                        <div class="pure-u-1 pure-u-md-3-5">
                            {% for doc in document.documents.all %}
                                <div><a href="{{doc.document.url}}" target="_blank">{{doc.designation}}</a></div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </section>
    <div class="pure-sec-accordion">
        {% for election in object.elections.all %}
            <section class="pure-sec-block" id="{{election.slug}}">
                <h3 class="pure-sec-title">
                    {{election.identifier}}<i class="ev-icon evi-sel-drk-dwn"></i>
                </h3>
                <div class="pure-sec-body full-row">
                    <div class="pure-g">
                        <div class="pure-u-1 pure-description">
                            {{election.description}}
                        </div>
                    </div>
                    <div class="pure-g pure-sec-row with-button small-text">
                        <div class="pure-u-1 pure-u-md-18-24">
                            <div class="vertical-align">
                                <label class="main-label">{% trans 'Current status' %}:</label>
                                <span>{{election.get_state_display}}</span>
                            </div>
                        </div>
                        <div class="pure-u-1 pure-u-md-6-24">
                            {% election_closed_for_voter request.user.pk election as el_closed_for_voter %}
                            {% if not el_closed_for_voter and show_vote_link %}
                                <a href="{% url 'voters:electoralprocess-voting' slug=object.slug %}" class="pure-button pure-button-primary pure-button-smooth full-width">{% trans 'Vote' %}</a>
                            {% else %}
                                <a href="#" class="pure-button pure-button-disabled pure-button-smooth full-width">{% trans 'Vote' %}</a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="pure-g pure-sec-row with-button small-text">
                        <div class="pure-u-1 pure-u-md-18-24">
                            <div class="pure-g">
                                <div class="pure-u-1 pure-u-md-3-8">
                                    <label class="main-label">{% trans 'Voting Time' %}:</label>
                                </div>
                                <div class="pure-u-1 pure-u-md-5-8">
                                    <div class="vertical-align">
                                        {% if election.is_voting_ended %}
                                            <label class="small-label simple">{% trans 'Closed' context "period" %}</label>
                                        {% else %}
                                            <i class="ev-icon evi-calendar"></i>
                                            <label class="small-label">{% trans 'Begin'%}: </label>{{election.voting_begin_date|date:'d-m-Y H:i'}}
                                            <label class="small-label">{% trans 'End'%}: </label>{{election.voting_end_date|date:'d-m-Y H:i'}}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pure-u-1 pure-u-md-6-24">
                            {% get_obj_perms request.user for election as "election_perms" %}
                            {% if "vote_election" in election_perms and election.state >= state_scrutinized %}
                                <a href="{% url 'voters:election-search-vote' slug=object.slug slug_election=election.slug %}" class="pure-button pure-button-secondary pure-button-smooth full-width">{% trans 'Browse vote references' %}</a>
                            {% else %}
                                <a href="#" class="pure-button pure-button-smooth full-width pure-button-disabled">{% trans 'Browse vote references' %}</a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="pure-g pure-sec-row with-button small-text">
                        <div class="pure-u-1 pure-u-md-18-24">
                            <div class="pure-g">
                                <div class="pure-u-1 pure-u-md-3-8">
                                    <label class="main-label">{% trans 'Complaint period for the electoral roll' %}:</label>
                                </div>
                                <div class="pure-u-1 pure-u-md-5-8">
                                    <div class="vertical-align">
                                        {% if election.is_complaint_period_ended %}
                                            <label class="small-label simple">{% trans 'Closed' context "period" %}</label>
                                        {% else %}
                                            <i class="ev-icon evi-calendar"></i>
                                            <label class="small-label">{% trans 'Begin'%}: </label>{{election.complaint_begin_date|date:'d-m-Y H:i'}}
                                            <label class="small-label">{% trans 'End'%}: </label>{{election.complaint_end_date|date:'d-m-Y H:i'}}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pure-u-1 pure-u-md-6-24">
                            {% with election.get_last_published_roll as published_roll %}
                                {% if published_roll %}
                                    <a href="{% url 'voters:electoralroll-detail' slug=object.slug slug_roll=published_roll.slug %}"
                                       class="pure-button pure-button-secondary pure-button-smooth full-width">
                                       {% trans 'Electoral roll' %}
                                    </a>
                                {% else %}
                                    <a href="#" class="pure-button pure-button-smooth pure-button-disabled full-width">
                                       {% trans 'Electoral roll' %}
                                    </a>
                                {% endif %}
                            {% endwith %}
                        </div>
                    </div>
                    {% if not election.write_in and election.candidates.not_write_in %}
                        <div class="pure-g pure-sec-row">
                            <div class="pure-u-1 pure-u-md-1-2">
                                <label class="main-label">{% trans 'Nominations for the election' %}</label>
                            </div>
                        </div>
                        {% for candidate in election.candidates.not_write_in %}
                            <div class="pure-g pure-sec-row pure-sec-tab">
                                <div class="pure-u-1 pure-u-md-3-5">{{candidate}}</div>
                                {% if candidate.documents.all %}
                                    <div class="pure-u-1 pure-u-md-2-5">
                                        {% for doc in candidate.documents.all %}
                                            <div><a href="{{doc.document.url}}" target="_blank">{{doc.designation}}</a></div>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </section>
        {% endfor %}
    </div>
</main>

evote/evotevotings/voters/templates/voters/includes/message_top.html
{% load i18n messages_tags %}

<div class="pure-g pure-gutter pure-title-row">
    <div class="pure-u-1 pure-u-md-1-2">
        <h1>{{title}}</h1>
    </div>
    <div class="pure-u-1 pure-u-md-1-2 ev-top-actions">
        <div class="pure-u-1-4 pull-right">
            <a href="{% url 'voters:messages-archived' %}" class="pure-button {% if is_archivedbox %}pure-button-primary{% else %}pure-button-secondary{% endif %} pure-button-round pull-right">{% trans 'Archived' %}</a>
        </div>
        <div class="pure-u-1-4 pull-right">
            <a href="{% url 'voters:messages-sent' %}" class="pure-button {% if is_sentbox %}pure-button-primary{% else %}pure-button-secondary{% endif %} pure-button-round pull-right">{% trans 'Sent' %}</a>
        </div>
        <div class="pure-u-1-4 pull-right">
            {% inbox_unread_count as unread_count %}
            <a href="{% url 'voters:messages-received' %}" class="pure-button {% if is_inbox %}pure-button-primary{% else %}pure-button-secondary{% endif %} pure-button-round pull-right">
                {% trans 'Received' %}
                {% if unread_count %}
                    ({{unread_count}})
                {% endif %}
            </a>
        </div>
    </div>
</div>

<div class="action-bar">
    <a href="{% url 'voters:messages-create' %}" class="pure-button pure-button-small nobg pure-button-primary pure-button-round">{% trans 'New' context 'message' %} <i class="ev-icon evi-new-msg"></i></a>
</div>

evote/evotevotings/voters/templates/voters/includes/vote_reference_list.html
{% for reference in references %}
    <li>{{reference}}</li>
{% endfor %}
{% if more %}
    <li>
        <a data-jscroll-next
           href="{% url 'voters:vote-reference-next-page' pk=electoral_process_id pk_election=election_id %}?page={{next_page}}&search={{search}}">more</a>
    </li>
{% endif %}